// Types for our cocktail data
export interface Ingredient {
  name: string;
  measure?: string;
  flavorProfile?: string;
  origin?: string;
  role?: string;
}

export interface Cocktail {
  id: string;
  name: string;
  image: string;
  category?: string;
  alcoholic?: string;
  glass?: string;
  instructions: string;
  ingredients: Ingredient[];
}

// Sample data - normally this would come from an API like TheCocktailDB
const cocktailsData: Cocktail[] = [
  {
    id: '1',
    name: 'Mojito',
    image: 'https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish with mint leaves and a lime wedge.',
    ingredients: [
      { 
        name: 'White rum', 
        measure: '2 oz',
        flavorProfile: 'Sweet, mild with vanilla notes',
        origin: 'Distilled from sugarcane molasses or juice, originating in the Caribbean',
        role: 'Base spirit that provides the alcoholic foundation'
      },
      { 
        name: 'Sugar', 
        measure: '2 tsp',
        flavorProfile: 'Sweet',
        origin: 'Refined from sugarcane or sugar beets',
        role: 'Sweetener that balances the acidity of lime juice'
      },
      { 
        name: 'Lime juice', 
        measure: '1 oz',
        flavorProfile: 'Sour, acidic, slightly sweet',
        origin: 'Extracted from lime fruits, native to Southeast Asia',
        role: 'Provides acidity and brightness to balance the sweetness'
      },
      { 
        name: 'Mint', 
        measure: '6 leaves',
        flavorProfile: 'Fresh, cool, slightly sweet',
        origin: 'Aromatic herb originally from the Mediterranean',
        role: 'Aromatic component that gives the mojito its distinctive fresh character'
      },
      { 
        name: 'Soda water', 
        measure: 'To fill',
        flavorProfile: 'Neutral, effervescent',
        origin: 'Carbonated water with added minerals',
        role: 'Dilutes and adds effervescence to the cocktail'
      },
    ],
  },
  {
    id: '2',
    name: 'Old Fashioned',
    image: 'https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Place sugar cube in old-fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey. Garnish with orange slice and a cherry.',
    ingredients: [
      { 
        name: 'Bourbon', 
        measure: '2 oz',
        flavorProfile: 'Rich, sweet, with notes of vanilla, oak, and caramel',
        origin: 'American whiskey made primarily from corn, originating in Kentucky',
        role: 'Primary spirit providing body and complex flavors'
      },
      { 
        name: 'Angostura bitters', 
        measure: '2 dashes',
        flavorProfile: 'Spicy, herbal, with notes of clove and cinnamon',
        origin: 'Created in Venezuela as a medicinal tincture in the 19th century',
        role: 'Adds complexity, depth, and balances sweetness'
      },
      { 
        name: 'Sugar cube', 
        measure: '1',
        flavorProfile: 'Sweet',
        origin: 'Refined from sugarcane or sugar beets',
        role: 'Adds sweetness to balance the bitterness and alcohol'
      },
      { 
        name: 'Water', 
        measure: 'dash',
        flavorProfile: 'Neutral',
        origin: 'Natural source',
        role: 'Helps dissolve sugar and dilutes the drink slightly'
      },
      { 
        name: 'Orange', 
        measure: '1 slice',
        flavorProfile: 'Sweet, citrusy',
        origin: 'Citrus fruit originally from Asia',
        role: 'Aromatic garnish that adds subtle citrus notes'
      },
      { 
        name: 'Maraschino cherry', 
        measure: '1',
        flavorProfile: 'Sweet, slightly tart',
        origin: 'Preserved cherries originating from Croatia',
        role: 'Decorative garnish that adds subtle sweetness'
      },
    ],
  },
  {
    id: '3',
    name: 'Negroni',
    image: 'https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Stir into glass over ice, garnish and serve.',
    ingredients: [
      { name: 'Gin', measure: '1 oz' },
      { name: 'Campari', measure: '1 oz' },
      { name: 'Sweet Vermouth', measure: '1 oz' },
      { name: 'Orange peel', measure: '1' },
    ],
  },
  {
    id: '4',
    name: 'Daiquiri',
    image: 'https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice, strain into a chilled cocktail glass, and serve.',
    ingredients: [
      { name: 'White rum', measure: '2 oz' },
      { name: 'Lime juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
    ],
  },
  {
    id: '5',
    name: 'Margarita',
    image: 'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.',
    ingredients: [
      { name: 'Tequila', measure: '2 oz' },
      { name: 'Triple sec', measure: '1 oz' },
      { name: 'Lime juice', measure: '1 oz' },
      { name: 'Salt', measure: '1 rim' },
    ],
  },
  {
    id: '6',
    name: 'Whiskey Sour',
    image: 'https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Shake with ice. Strain into chilled glass, garnish and serve.',
    ingredients: [
      { name: 'Bourbon', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Egg white', measure: '1/2 oz' },
      { name: 'Lemon slice', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '7',
    name: 'Manhattan',
    image: 'https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Stirred over ice, strained into a chilled glass, garnished, and served up.',
    ingredients: [
      { name: 'Bourbon', measure: '2 oz' },
      { name: 'Sweet Vermouth', measure: '1 oz' },
      { name: 'Angostura bitters', measure: '2 dashes' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '8',
    name: 'Cosmopolitan',
    image: 'https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Add all ingredients into cocktail shaker filled with ice. Shake well and double strain into chilled cocktail glass. Garnish with lime wheel.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Triple sec', measure: '1/2 oz' },
      { name: 'Cranberry juice', measure: '1/2 oz' },
      { name: 'Lime juice', measure: '1/4 oz' },
      { name: 'Lime wheel', measure: '1' },
    ],
  },
  {
    id: '9',
    name: 'Moscow Mule',
    image: 'https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Copper mug',
    instructions: 'Combine vodka and ginger beer in a copper mug filled with ice. Add lime juice and stir. Garnish with a lime wedge.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Ginger beer', measure: '4 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '10',
    name: 'Piña Colada',
    image: 'https://www.thecocktaildb.com/images/media/drink/cpf4j51504371346.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Blend all ingredients with ice until smooth. Pour into hurricane glass and garnish with pineapple and cherry.',
    ingredients: [
      { name: 'White rum', measure: '2 oz' },
      { name: 'Coconut cream', measure: '1 oz' },
      { name: 'Pineapple juice', measure: '3 oz' },
      { name: 'Pineapple wedge', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '11',
    name: 'Martini',
    image: 'https://www.thecocktaildb.com/images/media/drink/71t8581504353095.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.',
    ingredients: [
      { name: 'Gin', measure: '2.5 oz' },
      { name: 'Dry Vermouth', measure: '1/2 oz' },
      { name: 'Olive', measure: '1' },
    ],
  },
  {
    id: '12',
    name: 'Bloody Mary',
    image: 'https://www.thecocktaildb.com/images/media/drink/t6caa21582485702.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Stirring gently, pour all ingredients into highball glass. Garnish with celery stalk and lime wedge.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Tomato juice', measure: '4 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Worcestershire sauce', measure: '3 dashes' },
      { name: 'Tabasco sauce', measure: '3 dashes' },
      { name: 'Celery salt', measure: '1 pinch' },
      { name: 'Celery stalk', measure: '1' },
    ],
  },
  {
    id: '13',
    name: 'Mai Tai',
    image: 'https://www.thecocktaildb.com/images/media/drink/twyrrp1439907470.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Shake all ingredients with ice. Strain into glass over fresh ice. Garnish with pineapple and cherry.',
    ingredients: [
      { name: 'White rum', measure: '1 oz' },
      { name: 'Dark rum', measure: '1 oz' },
      { name: 'Orange Curacao', measure: '1/2 oz' },
      { name: 'Orgeat syrup', measure: '1/2 oz' },
      { name: 'Lime juice', measure: '1 oz' },
      { name: 'Pineapple wedge', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '14',
    name: 'Gimlet',
    image: 'https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake with ice and strain into a chilled cocktail glass. Garnish with lime wheel.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Lime juice', measure: '3/4 oz' },
      { name: 'Simple syrup', measure: '3/4 oz' },
      { name: 'Lime wheel', measure: '1' },
    ],
  },
  {
    id: '15',
    name: 'Sidecar',
    image: 'https://www.thecocktaildb.com/images/media/drink/x72sik1606854479.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Pour all ingredients into cocktail shaker filled with ice cubes. Shake well and strain into cocktail glass.',
    ingredients: [
      { name: 'Cognac', measure: '2 oz' },
      { name: 'Triple sec', measure: '1 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
    ],
  },
  {
    id: '16',
    name: 'Mint Julep',
    image: 'https://www.thecocktaildb.com/images/media/drink/squyyq1439907312.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'In a highball glass gently muddle the mint, sugar and water. Fill the glass with cracked ice, add Bourbon and stir well until the glass is well frosted. Garnish with a sprig of fresh mint.',
    ingredients: [
      { name: 'Bourbon', measure: '2.5 oz' },
      { name: 'Sugar', measure: '1 tsp' },
      { name: 'Mint', measure: '4 leaves' },
      { name: 'Water', measure: '2 tsp' },
    ],
  },
  {
    id: '17',
    name: 'Sazerac',
    image: 'https://www.thecocktaildb.com/images/media/drink/vvpxwy1439907208.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice and set it aside. Discard the ice and any excess absinthe from the prepared glass, and strain the drink into the glass. Add the lemon peel for garnish.',
    ingredients: [
      { name: 'Rye whiskey', measure: '2 oz' },
      { name: 'Absinthe', measure: '1/4 oz' },
      { name: 'Sugar cube', measure: '1' },
      { name: 'Peychaud bitters', measure: '2 dashes' },
      { name: 'Lemon peel', measure: '1' },
    ],
  },
  {
    id: '18',
    name: 'Ramos Gin Fizz',
    image: 'https://www.thecocktaildb.com/images/media/drink/967t911643844053.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Shake all ingredients (except soda water) with ice for 12 minutes. Strain into a highball glass and top with soda water.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Egg white', measure: '1' },
      { name: 'Heavy cream', measure: '1 oz' },
      { name: 'Soda water', measure: 'Top' },
    ],
  },
  {
    id: '19',
    name: 'Aviation',
    image: 'https://www.thecocktaildb.com/images/media/drink/ruutxt1478253328.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Add all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass. Garnish with a cherry.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Maraschino liqueur', measure: '1/2 oz' },
      { name: 'Crème de Violette', measure: '1/4 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '20',
    name: 'Vieux Carré',
    image: 'https://www.thecocktaildb.com/images/media/drink/4o6xal1550454100.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Stir all ingredients with ice and strain into an old-fashioned glass over a large ice cube. Garnish with lemon twist.',
    ingredients: [
      { name: 'Rye whiskey', measure: '1 oz' },
      { name: 'Cognac', measure: '1 oz' },
      { name: 'Sweet Vermouth', measure: '1 oz' },
      { name: 'Bénédictine', measure: '1/4 oz' },
      { name: 'Angostura bitters', measure: '2 dashes' },
      { name: 'Peychaud bitters', measure: '2 dashes' },
      { name: 'Lemon twist', measure: '1' },
    ],
  },
  {
    id: '21',
    name: 'Tom Collins',
    image: 'https://www.thecocktaildb.com/images/media/drink/qyqqtu1468878544.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'In a shaker half-filled with ice cubes, combine the gin, lemon juice, and sugar. Shake well. Strain into a collins glass almost filled with ice cubes. Add the club soda. Stir and garnish with the cherry and the orange slice.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Soda water', measure: 'Top' },
      { name: 'Maraschino cherry', measure: '1' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '22',
    name: 'French 75',
    image: 'https://www.thecocktaildb.com/images/media/drink/hrxfbl1606773109.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Champagne flute',
    instructions: 'Combine gin, lemon juice, and sugar in a cocktail shaker filled with ice. Shake vigorously and strain into a champagne flute. Top with champagne and garnish with lemon twist.',
    ingredients: [
      { name: 'Gin', measure: '1 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Champagne', measure: '2 oz' },
      { name: 'Lemon twist', measure: '1' },
    ],
  },
  {
    id: '23',
    name: 'Boulevardier',
    image: 'https://www.thecocktaildb.com/images/media/drink/km84qi1513705868.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Stir all ingredients with ice and strain into an old-fashioned glass over a large ice cube. Garnish with orange peel.',
    ingredients: [
      { name: 'Bourbon', measure: '2 oz' },
      { name: 'Campari', measure: '1 oz' },
      { name: 'Sweet Vermouth', measure: '1 oz' },
      { name: 'Orange peel', measure: '1' },
    ],
  },
  {
    id: '24',
    name: 'Paper Plane',
    image: 'https://www.thecocktaildb.com/images/media/drink/qyqtpv1468923726.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Add all ingredients to a shaker filled with ice. Shake and strain into a chilled coupe glass.',
    ingredients: [
      { name: 'Bourbon', measure: '3/4 oz' },
      { name: 'Aperol', measure: '3/4 oz' },
      { name: 'Amaro Nonino', measure: '3/4 oz' },
      { name: 'Lemon juice', measure: '3/4 oz' },
    ],
  },
  {
    id: '25',
    name: 'Last Word',
    image: 'https://www.thecocktaildb.com/images/media/drink/91oule1513702624.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Add all ingredients to a shaker filled with ice. Shake and strain into a chilled coupe glass.',
    ingredients: [
      { name: 'Gin', measure: '3/4 oz' },
      { name: 'Green Chartreuse', measure: '3/4 oz' },
      { name: 'Maraschino liqueur', measure: '3/4 oz' },
      { name: 'Lime juice', measure: '3/4 oz' },
    ],
  },
  {
    id: '26',
    name: 'Bee\'s Knees',
    image: 'https://www.thecocktaildb.com/images/media/drink/tx8ne41582475326.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice and strain into a chilled cocktail glass.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Honey syrup', measure: '3/4 oz' },
      { name: 'Lemon juice', measure: '3/4 oz' },
    ],
  },
  {
    id: '27',
    name: 'Southside',
    image: 'https://www.thecocktaildb.com/images/media/drink/nm00f91578877337.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Muddle mint in shaker. Add gin, lime juice, and simple syrup. Shake with ice and double strain into chilled cocktail glass. Garnish with mint sprig.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Lime juice', measure: '3/4 oz' },
      { name: 'Simple syrup', measure: '3/4 oz' },
      { name: 'Mint', measure: '8 leaves' },
    ],
  },
  {
    id: '28',
    name: 'Corpse Reviver No. 2',
    image: 'https://www.thecocktaildb.com/images/media/drink/gifgao1513704334.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice and strain into a chilled cocktail glass. Rinse glass with absinthe before straining.',
    ingredients: [
      { name: 'Gin', measure: '3/4 oz' },
      { name: 'Triple sec', measure: '3/4 oz' },
      { name: 'Lillet Blanc', measure: '3/4 oz' },
      { name: 'Lemon juice', measure: '3/4 oz' },
      { name: 'Absinthe', measure: '1 dash' },
    ],
  },
  {
    id: '29',
    name: 'Clover Club',
    image: 'https://www.thecocktaildb.com/images/media/drink/qt32161579090109.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Dry shake all ingredients, then shake with ice. Double strain into chilled cocktail glass.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Lemon juice', measure: '3/4 oz' },
      { name: 'Raspberry syrup', measure: '1/2 oz' },
      { name: 'Egg white', measure: '1' },
    ],
  },
  {
    id: '30',
    name: 'Gold Rush',
    image: 'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Shake all ingredients with ice and strain into an old-fashioned glass over ice.',
    ingredients: [
      { name: 'Bourbon', measure: '2 oz' },
      { name: 'Honey syrup', measure: '3/4 oz' },
      { name: 'Lemon juice', measure: '3/4 oz' },
    ],
  },
  {
    id: '31',
    name: 'Penicillin',
    image: 'https://www.thecocktaildb.com/images/media/drink/hc9y1q1582482093.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Muddle ginger in shaker. Add scotch, lemon juice, and honey syrup. Shake with ice and strain into old-fashioned glass over ice. Float Islay scotch on top.',
    ingredients: [
      { name: 'Scotch whisky', measure: '2 oz' },
      { name: 'Lemon juice', measure: '3/4 oz' },
      { name: 'Honey syrup', measure: '3/4 oz' },
      { name: 'Ginger', measure: '3 slices' },
      { name: 'Islay scotch', measure: '1/4 oz' },
    ],
  },
  {
    id: '32',
    name: 'Paloma',
    image: 'https://www.thecocktaildb.com/images/media/drink/samm5j1513706393.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Add tequila and lime juice to a glass filled with ice. Top with grapefruit soda and stir gently. Garnish with lime wedge.',
    ingredients: [
      { name: 'Tequila', measure: '2 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Grapefruit soda', measure: '4 oz' },
      { name: 'Salt', measure: '1 pinch' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '33',
    name: 'Espresso Martini',
    image: 'https://www.thecocktaildb.com/images/media/drink/n0sx531504372951.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Pour ingredients into cocktail shaker filled with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with coffee beans.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Coffee liqueur', measure: '1/2 oz' },
      { name: 'Espresso', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/4 oz' },
      { name: 'Coffee beans', measure: '3' },
    ],
  },
  {
    id: '34',
    name: 'Dark \'n\' Stormy',
    image: 'https://www.thecocktaildb.com/images/media/drink/t1tn0s1504374905.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'In a highball glass filled with ice add rum. Top with ginger beer and garnish with lime wedge.',
    ingredients: [
      { name: 'Dark rum', measure: '2 oz' },
      { name: 'Ginger beer', measure: '4 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '35',
    name: 'Bramble',
    image: 'https://www.thecocktaildb.com/images/media/drink/twtbh51630406392.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Build gin, lemon juice and simple syrup in an old-fashioned glass filled with crushed ice. Drizzle blackberry liqueur over the top and garnish with blackberries and lemon slice.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Blackberry liqueur', measure: '1/2 oz' },
      { name: 'Blackberries', measure: '2' },
      { name: 'Lemon slice', measure: '1' },
    ],
  },
  {
    id: '36',
    name: 'Pisco Sour',
    image: 'https://www.thecocktaildb.com/images/media/drink/8ofgr31606772327.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Dry shake all ingredients, then shake with ice. Double strain into chilled cocktail glass. Garnish with bitters dots.',
    ingredients: [
      { name: 'Pisco', measure: '2 oz' },
      { name: 'Lime juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '3/4 oz' },
      { name: 'Egg white', measure: '1' },
      { name: 'Angostura bitters', measure: '3 dashes' },
    ],
  },
  {
    id: '37',
    name: 'Amaretto Sour',
    image: 'https://www.thecocktaildb.com/images/media/drink/xnzc541493070211.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Shake ingredients with ice and strain into an old-fashioned glass over ice. Garnish with cherry and orange slice.',
    ingredients: [
      { name: 'Amaretto', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Egg white', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '38',
    name: 'Caipirinha',
    image: 'https://www.thecocktaildb.com/images/media/drink/jbqtwi1513703225.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Muddle lime wedges and sugar in old-fashioned glass. Add cachaça and fill with ice. Stir well.',
    ingredients: [
      { name: 'Cachaça', measure: '2 oz' },
      { name: 'Lime', measure: '1/2' },
      { name: 'Sugar', measure: '2 tsp' },
    ],
  },
  {
    id: '39',
    name: 'Aperol Spritz',
    image: 'https://www.thecocktaildb.com/images/media/drink/iloasq1587661955.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Wine glass',
    instructions: 'Build in wine glass over ice. Garnish with orange slice.',
    ingredients: [
      { name: 'Aperol', measure: '3 oz' },
      { name: 'Prosecco', measure: '3 oz' },
      { name: 'Soda water', measure: '1 oz' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '40',
    name: 'Campari Spritz',
    image: 'https://www.thecocktaildb.com/images/media/drink/cskl4t1643932906.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Wine glass',
    instructions: 'Build in wine glass over ice. Garnish with orange slice.',
    ingredients: [
      { name: 'Campari', measure: '2 oz' },
      { name: 'Prosecco', measure: '3 oz' },
      { name: 'Soda water', measure: '1 oz' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '41',
    name: 'Hugo Spritz',
    image: 'https://www.thecocktaildb.com/images/media/drink/7y3o9t1643932851.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Wine glass',
    instructions: 'Build in wine glass over ice. Garnish with mint and lime.',
    ingredients: [
      { name: 'Elderflower liqueur', measure: '1 oz' },
      { name: 'Prosecco', measure: '4 oz' },
      { name: 'Soda water', measure: '2 oz' },
      { name: 'Mint', measure: '6 leaves' },
      { name: 'Lime wheel', measure: '1' },
    ],
  },
  {
    id: '42',
    name: 'Bellini',
    image: 'https://www.thecocktaildb.com/images/media/drink/eaag491504367543.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Champagne flute',
    instructions: 'Pour peach purée into champagne flute and top with prosecco. Stir gently.',
    ingredients: [
      { name: 'Peach purée', measure: '2 oz' },
      { name: 'Prosecco', measure: '4 oz' },
    ],
  },
  {
    id: '43',
    name: 'Mimosa',
    image: 'https://www.thecocktaildb.com/images/media/drink/juhcuu1504370685.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Champagne flute',
    instructions: 'Pour orange juice into champagne flute and top with champagne. Garnish with orange slice.',
    ingredients: [
      { name: 'Orange juice', measure: '3 oz' },
      { name: 'Champagne', measure: '3 oz' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '44',
    name: 'Kir Royale',
    image: 'https://www.thecocktaildb.com/images/media/drink/yt3i6x1504369052.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Champagne flute',
    instructions: 'Pour cassis into champagne flute and top with champagne.',
    ingredients: [
      { name: 'Crème de cassis', measure: '1/2 oz' },
      { name: 'Champagne', measure: '4 oz' },
    ],
  },
  {
    id: '45',
    name: 'Black Russian',
    image: 'https://www.thecocktaildb.com/images/media/drink/9a9bg51511290151.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Pour ingredients into old-fashioned glass over ice and stir.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Coffee liqueur', measure: '1 oz' },
    ],
  },
  {
    id: '46',
    name: 'White Russian',
    image: 'https://www.thecocktaildb.com/images/media/drink/vsrup61472405821.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Pour vodka and coffee liqueur over ice cubes in an old-fashioned glass. Fill with light cream and serve.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Coffee liqueur', measure: '1 oz' },
      { name: 'Heavy cream', measure: '1 oz' },
    ],
  },
  {
    id: '47',
    name: 'Mudslide',
    image: 'https://www.thecocktaildb.com/images/media/drink/ttyvxr1472668064.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Combine vodka, coffee liqueur, and Irish cream in an old-fashioned glass over ice. Stir gently.',
    ingredients: [
      { name: 'Vodka', measure: '1 oz' },
      { name: 'Coffee liqueur', measure: '1 oz' },
      { name: 'Irish cream', measure: '1 oz' },
    ],
  },
  {
    id: '48',
    name: 'Rusty Nail',
    image: 'https://www.thecocktaildb.com/images/media/drink/yqsvtw1478252982.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Pour scotch and Drambuie into old-fashioned glass over ice. Stir gently.',
    ingredients: [
      { name: 'Scotch whisky', measure: '2 oz' },
      { name: 'Drambuie', measure: '1/2 oz' },
    ],
  },
  {
    id: '49',
    name: 'Godfather',
    image: 'https://www.thecocktaildb.com/images/media/drink/vuywiw1472405495.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Pour scotch and amaretto into old-fashioned glass over ice. Stir gently.',
    ingredients: [
      { name: 'Scotch whisky', measure: '2 oz' },
      { name: 'Amaretto', measure: '1/2 oz' },
    ],
  },
  {
    id: '50',
    name: 'Godmother',
    image: 'https://www.thecocktaildb.com/images/media/drink/qrwvps1478963017.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Pour vodka and amaretto into old-fashioned glass over ice. Stir gently.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Amaretto', measure: '1/2 oz' },
    ],
  },
  {
    id: '51',
    name: 'B-52',
    image: 'https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg',
    category: 'Shot',
    alcoholic: 'Alcoholic',
    glass: 'Shot glass',
    instructions: 'Layer the ingredients in a shot glass in the order given.',
    ingredients: [
      { name: 'Coffee liqueur', measure: '1/3 oz' },
      { name: 'Irish cream', measure: '1/3 oz' },
      { name: 'Grand Marnier', measure: '1/3 oz' },
    ],
  },
  {
    id: '52',
    name: 'Kamikaze',
    image: 'https://www.thecocktaildb.com/images/media/drink/rqwus61478963017.jpg',
    category: 'Shot',
    alcoholic: 'Alcoholic',
    glass: 'Shot glass',
    instructions: 'Shake all ingredients with ice and strain into shot glass.',
    ingredients: [
      { name: 'Vodka', measure: '1 oz' },
      { name: 'Triple sec', measure: '1/2 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
    ],
  },
  {
    id: '53',
    name: 'Lemon Drop Shot',
    image: 'https://www.thecocktaildb.com/images/media/drink/mtpxgk1504373297.jpg',
    category: 'Shot',
    alcoholic: 'Alcoholic',
    glass: 'Shot glass',
    instructions: 'Shake vodka and lemon juice with ice. Strain into sugar-rimmed shot glass.',
    ingredients: [
      { name: 'Vodka', measure: '1 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Sugar', measure: 'Rim' },
    ],
  },
  {
    id: '54',
    name: 'Blue Lagoon',
    image: 'https://www.thecocktaildb.com/images/media/drink/5vxlsr1598917702.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Pour vodka and blue curaçao over ice in highball glass. Top with lemonade and garnish with cherry.',
    ingredients: [
      { name: 'Vodka', measure: '1 oz' },
      { name: 'Blue Curacao', measure: '1 oz' },
      { name: 'Lemonade', measure: '4 oz' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '55',
    name: 'Sex on the Beach',
    image: 'https://www.thecocktaildb.com/images/media/drink/fi67x01504370820.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build all ingredients in a highball glass filled with ice. Garnish with pineapple and cherry.',
    ingredients: [
      { name: 'Vodka', measure: '1 oz' },
      { name: 'Peach schnapps', measure: '1 oz' },
      { name: 'Cranberry juice', measure: '2 oz' },
      { name: 'Pineapple juice', measure: '2 oz' },
      { name: 'Pineapple wedge', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '56',
    name: 'Tequila Sunrise',
    image: 'https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Pour tequila and orange juice into highball glass over ice. Slowly pour grenadine down side of glass to create layered effect.',
    ingredients: [
      { name: 'Tequila', measure: '2 oz' },
      { name: 'Orange juice', measure: '4 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Orange slice', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '57',
    name: 'Bahama Mama',
    image: 'https://www.thecocktaildb.com/images/media/drink/tyb4a41515527564.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Add all ingredients to a hurricane glass filled with ice. Stir and garnish with pineapple and cherry.',
    ingredients: [
      { name: 'White rum', measure: '1 oz' },
      { name: 'Dark rum', measure: '1 oz' },
      { name: 'Coconut rum', measure: '1 oz' },
      { name: 'Pineapple juice', measure: '2 oz' },
      { name: 'Orange juice', measure: '1 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Pineapple wedge', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '58',
    name: 'Long Island Iced Tea',
    image: 'https://www.thecocktaildb.com/images/media/drink/xvuqlh1472405418.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Combine all spirits and sour mix in a highball glass filled with ice. Top with cola and garnish with lemon wedge.',
    ingredients: [
      { name: 'Vodka', measure: '1/2 oz' },
      { name: 'White rum', measure: '1/2 oz' },
      { name: 'Gin', measure: '1/2 oz' },
      { name: 'Tequila', measure: '1/2 oz' },
      { name: 'Triple sec', measure: '1/2 oz' },
      { name: 'Sour mix', measure: '1 oz' },
      { name: 'Cola', measure: 'Top' },
      { name: 'Lemon wedge', measure: '1' },
    ],
  },
  {
    id: '59',
    name: 'AMF (Adios Mother F***er)',
    image: 'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Combine all spirits and sour mix in a highball glass filled with ice. Top with lemon-lime soda and garnish with lemon wedge.',
    ingredients: [
      { name: 'Vodka', measure: '1/2 oz' },
      { name: 'White rum', measure: '1/2 oz' },
      { name: 'Gin', measure: '1/2 oz' },
      { name: 'Tequila', measure: '1/2 oz' },
      { name: 'Blue Curacao', measure: '1/2 oz' },
      { name: 'Sour mix', measure: '1 oz' },
      { name: 'Lemon-lime soda', measure: 'Top' },
      { name: 'Lemon wedge', measure: '1' },
    ],
  },
  {
    id: '60',
    name: 'Zombie',
    image: 'https://www.thecocktaildb.com/images/media/drink/s2daou1606768940.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Blend all ingredients with ice and pour into hurricane glass. Garnish with mint sprig and cherry.',
    ingredients: [
      { name: 'White rum', measure: '1 oz' },
      { name: 'Golden rum', measure: '1 oz' },
      { name: 'Dark rum', measure: '1 oz' },
      { name: 'Apricot brandy', measure: '1/2 oz' },
      { name: 'Pineapple juice', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Mint', measure: '1 sprig' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '61',
    name: 'Hurricane',
    image: 'https://www.thecocktaildb.com/images/media/drink/cqrys11515077562.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Shake all ingredients with ice and pour into hurricane glass. Garnish with orange slice and cherry.',
    ingredients: [
      { name: 'White rum', measure: '1 oz' },
      { name: 'Dark rum', measure: '1 oz' },
      { name: 'Passion fruit syrup', measure: '1 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Orange slice', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '62',
    name: 'Painkiller',
    image: 'https://www.thecocktaildb.com/images/media/drink/lme6k81623435395.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Shake all ingredients with ice and strain into hurricane glass over ice. Garnish with orange slice and cherry. Dust with nutmeg.',
    ingredients: [
      { name: 'Dark rum', measure: '2 oz' },
      { name: 'Pineapple juice', measure: '4 oz' },
      { name: 'Orange juice', measure: '1 oz' },
      { name: 'Coconut cream', measure: '1 oz' },
      { name: 'Nutmeg', measure: 'Pinch' },
      { name: 'Orange slice', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '63',
    name: 'Planter\'s Punch',
    image: 'https://www.thecocktaildb.com/images/media/drink/p-_nqn1493072720.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Shake all ingredients with ice and strain into hurricane glass over ice. Garnish with pineapple and cherry.',
    ingredients: [
      { name: 'Dark rum', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Angostura bitters', measure: '2 dashes' },
      { name: 'Pineapple wedge', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '64',
    name: 'Jungle Bird',
    image: 'https://www.thecocktaildb.com/images/media/drink/kcqaek1623435397.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Shake all ingredients with ice and strain into old-fashioned glass over ice. Garnish with pineapple wedge.',
    ingredients: [
      { name: 'Dark rum', measure: '2 oz' },
      { name: 'Campari', measure: '3/4 oz' },
      { name: 'Pineapple juice', measure: '1.5 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Pineapple wedge', measure: '1' },
    ],
  },
  {
    id: '65',
    name: 'Ti\' Punch',
    image: 'https://www.thecocktaildb.com/images/media/drink/bmovwe1623435351.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Muddle lime wheel with cane syrup in old-fashioned glass. Add rhum agricole and stir. Add ice if desired.',
    ingredients: [
      { name: 'Rhum agricole', measure: '2 oz' },
      { name: 'Cane syrup', measure: '1/4 oz' },
      { name: 'Lime wheel', measure: '1' },
    ],
  },
  {
    id: '66',
    name: 'Rum Punch',
    image: 'https://www.thecocktaildb.com/images/media/drink/5pj1441624347.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Mix all ingredients in hurricane glass over ice. Garnish with orange slice and cherry.',
    ingredients: [
      { name: 'Dark rum', measure: '2 oz' },
      { name: 'Lime juice', measure: '1 oz' },
      { name: 'Orange juice', measure: '2 oz' },
      { name: 'Pineapple juice', measure: '2 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Orange slice', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '67',
    name: 'Cuba Libre',
    image: 'https://www.thecocktaildb.com/images/media/drink/eamwmx1604774687.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with lime wedge.',
    ingredients: [
      { name: 'White rum', measure: '2 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Cola', measure: '4 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '68',
    name: 'Rum and Coke',
    image: 'https://www.thecocktaildb.com/images/media/drink/qtibrt1606771671.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice.',
    ingredients: [
      { name: 'White rum', measure: '2 oz' },
      { name: 'Cola', measure: '4 oz' },
    ],
  },
  {
    id: '69',
    name: 'Vodka Tonic',
    image: 'https://www.thecocktaildb.com/images/media/drink/9koz3f1643821062.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with lime wedge.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Tonic water', measure: '4 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '70',
    name: 'Gin and Tonic',
    image: 'https://www.thecocktaildb.com/images/media/drink/pzwkmt1656186176.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with lime wedge.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Tonic water', measure: '4 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '71',
    name: 'Scotch and Soda',
    image: 'https://www.thecocktaildb.com/images/media/drink/qxvryu1472405618.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice.',
    ingredients: [
      { name: 'Scotch whisky', measure: '2 oz' },
      { name: 'Soda water', measure: '4 oz' },
    ],
  },
  {
    id: '72',
    name: 'Bourbon and Branch',
    image: 'https://www.thecocktaildb.com/images/media/drink/txtxtr1468878384.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Pour bourbon into old-fashioned glass over ice. Add branch water to taste.',
    ingredients: [
      { name: 'Bourbon', measure: '2 oz' },
      { name: 'Water', measure: 'To taste' },
    ],
  },
  {
    id: '73',
    name: 'Cape Codder',
    image: 'https://www.thecocktaildb.com/images/media/drink/tpx91t1466365633.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with lime wedge.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Cranberry juice', measure: '4 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '74',
    name: 'Bay Breeze',
    image: 'https://www.thecocktaildb.com/images/media/drink/xwqruw1472409624.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with lime wedge.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Cranberry juice', measure: '2 oz' },
      { name: 'Pineapple juice', measure: '2 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '75',
    name: 'Sea Breeze',
    image: 'https://www.thecocktaildb.com/images/media/drink/5pj1441624347.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with lime wedge.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Cranberry juice', measure: '2 oz' },
      { name: 'Grapefruit juice', measure: '2 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '76',
    name: 'Madras',
    image: 'https://www.thecocktaildb.com/images/media/drink/wtt3jx1462906085.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with lime wedge.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Cranberry juice', measure: '2 oz' },
      { name: 'Orange juice', measure: '2 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '77',
    name: 'Greyhound',
    image: 'https://www.thecocktaildb.com/images/media/drink/1wqrkf1468878473.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Grapefruit juice', measure: '4 oz' },
    ],
  },
  {
    id: '78',
    name: 'Salty Dog',
    image: 'https://www.thecocktaildb.com/images/media/drink/7ltqsj1567600652.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in salt-rimmed highball glass over ice.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Grapefruit juice', measure: '4 oz' },
      { name: 'Salt', measure: 'Rim' },
    ],
  },
  {
    id: '79',
    name: 'Screwdriver',
    image: 'https://www.thecocktaildb.com/images/media/drink/8xnykt1504352207.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build vodka and orange juice in highball glass over ice. Garnish with orange slice.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Orange juice', measure: '4 oz' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '80',
    name: 'Harvey Wallbanger',
    image: 'https://www.thecocktaildb.com/images/media/drink/vtrtrx1468877640.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build vodka and orange juice in highball glass over ice. Float Galliano on top. Garnish with orange slice and cherry.',
    ingredients: [
      { name: 'Vodka', measure: '1 oz' },
      { name: 'Orange juice', measure: '4 oz' },
      { name: 'Galliano', measure: '1/2 oz' },
      { name: 'Orange slice', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '81',
    name: 'Fuzzy Navel',
    image: 'https://www.thecocktaildb.com/images/media/drink/vtytw01468877655.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with orange slice.',
    ingredients: [
      { name: 'Peach schnapps', measure: '2 oz' },
      { name: 'Orange juice', measure: '4 oz' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '82',
    name: 'Hairy Navel',
    image: 'https://www.thecocktaildb.com/images/media/drink/qtvsur1468877665.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Build in highball glass over ice. Garnish with orange slice.',
    ingredients: [
      { name: 'Vodka', measure: '1 oz' },
      { name: 'Peach schnapps', measure: '1 oz' },
      { name: 'Orange juice', measure: '4 oz' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '83',
    name: 'Sloe Gin Fizz',
    image: 'https://www.thecocktaildb.com/images/media/drink/rqu5yt1492804309.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Shake sloe gin, lemon juice, and sugar with ice. Strain into highball glass over ice and top with soda water.',
    ingredients: [
      { name: 'Sloe gin', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Soda water', measure: 'Top' },
    ],
  },
  {
    id: '84',
    name: 'Singapore Sling',
    image: 'https://www.thecocktaildb.com/images/media/drink/8rjtqt1556577128.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Hurricane glass',
    instructions: 'Shake all ingredients (except cherry brandy) with ice. Strain into hurricane glass over ice. Float cherry brandy on top. Garnish with pineapple and cherry.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Cherry brandy', measure: '1/2 oz' },
      { name: 'Triple sec', measure: '1/4 oz' },
      { name: 'Bénédictine', measure: '1/4 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Pineapple juice', measure: '4 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Angostura bitters', measure: '1 dash' },
      { name: 'Pineapple wedge', measure: '1' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '85',
    name: 'Brandy Alexander',
    image: 'https://www.thecocktaildb.com/images/media/drink/3axl5r1493068575.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice and strain into cocktail glass. Garnish with nutmeg.',
    ingredients: [
      { name: 'Cognac', measure: '1.5 oz' },
      { name: 'Crème de cacao', measure: '1 oz' },
      { name: 'Heavy cream', measure: '1 oz' },
      { name: 'Nutmeg', measure: 'Pinch' },
    ],
  },
  {
    id: '86',
    name: 'Grasshopper',
    image: 'https://www.thecocktaildb.com/images/media/drink/7c7w9t1504371166.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice and strain into cocktail glass.',
    ingredients: [
      { name: 'Crème de menthe', measure: '1 oz' },
      { name: 'Crème de cacao', measure: '1 oz' },
      { name: 'Heavy cream', measure: '1 oz' },
    ],
  },
  {
    id: '87',
    name: 'Pink Lady',
    image: 'https://www.thecocktaildb.com/images/media/drink/a7rrqe1544215577.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Dry shake all ingredients, then shake with ice. Double strain into chilled cocktail glass.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Egg white', measure: '1' },
    ],
  },
  {
    id: '88',
    name: 'Ward 8',
    image: 'https://www.thecocktaildb.com/images/media/drink/xyppur1578965573.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice and strain into cocktail glass. Garnish with cherry.',
    ingredients: [
      { name: 'Rye whiskey', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Orange juice', measure: '1/2 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Maraschino cherry', measure: '1' },
    ],
  },
  {
    id: '89',
    name: 'Jack Rose',
    image: 'https://www.thecocktaildb.com/images/media/drink/rvxtyz1468877699.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice and strain into cocktail glass.',
    ingredients: [
      { name: 'Applejack', measure: '2 oz' },
      { name: 'Grenadine', measure: '1/2 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
    ],
  },
  {
    id: '90',
    name: 'Between the Sheets',
    image: 'https://www.thecocktaildb.com/images/media/drink/tpeuqq1549513945.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Cocktail glass',
    instructions: 'Shake all ingredients with ice and strain into cocktail glass.',
    ingredients: [
      { name: 'Cognac', measure: '1 oz' },
      { name: 'White rum', measure: '1 oz' },
      { name: 'Triple sec', measure: '1 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
    ],
  },
  {
    id: '91',
    name: 'Stinger',
    image: 'https://www.thecocktaildb.com/images/media/drink/0kuydf1606764375.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Stir ingredients with ice and strain into old-fashioned glass over ice.',
    ingredients: [
      { name: 'Cognac', measure: '2 oz' },
      { name: 'Crème de menthe', measure: '1/2 oz' },
    ],
  },
  {
    id: '92',
    name: 'Brandy Crusta',
    image: 'https://www.thecocktaildb.com/images/media/drink/2u6sts1514506210.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Wine glass',
    instructions: 'Rim wine glass with sugar. Shake all ingredients with ice and strain into prepared glass. Garnish with lemon peel.',
    ingredients: [
      { name: 'Cognac', measure: '2 oz' },
      { name: 'Triple sec', measure: '1/2 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Simple syrup', measure: '1/4 oz' },
      { name: 'Angostura bitters', measure: '2 dashes' },
      { name: 'Sugar', measure: 'Rim' },
      { name: 'Lemon peel', measure: '1' },
    ],
  },
  {
    id: '93',
    name: 'Brandy Smash',
    image: 'https://www.thecocktaildb.com/images/media/drink/djs5ex1606764375.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Muddle mint with simple syrup in old-fashioned glass. Add cognac and fill with crushed ice. Garnish with mint sprig.',
    ingredients: [
      { name: 'Cognac', measure: '2 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Mint', measure: '8 leaves' },
    ],
  },
  {
    id: '94',
    name: 'Brandy Milk Punch',
    image: 'https://www.thecocktaildb.com/images/media/drink/xayp6v1606765491.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Shake all ingredients with ice and strain into old-fashioned glass over ice. Garnish with nutmeg.',
    ingredients: [
      { name: 'Cognac', measure: '2 oz' },
      { name: 'Milk', measure: '4 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Vanilla extract', measure: '2 drops' },
      { name: 'Nutmeg', measure: 'Pinch' },
    ],
  },
  {
    id: '95',
    name: 'Ramos Fizz',
    image: 'https://www.thecocktaildb.com/images/media/drink/967t911643844053.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Shake all ingredients (except soda water) for 12 minutes. Strain into highball glass and top with soda water.',
    ingredients: [
      { name: 'Gin', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Egg white', measure: '1' },
      { name: 'Heavy cream', measure: '1 oz' },
      { name: 'Orange flower water', measure: '3 drops' },
      { name: 'Soda water', measure: 'Top' },
    ],
  },
  {
    id: '96',
    name: 'John Collins',
    image: 'https://www.thecocktaildb.com/images/media/drink/2fg8et1513705778.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Shake bourbon, lemon juice, and simple syrup with ice. Strain into collins glass over ice and top with soda water. Garnish with cherry and orange slice.',
    ingredients: [
      { name: 'Bourbon', measure: '2 oz' },
      { name: 'Lemon juice', measure: '1 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Soda water', measure: 'Top' },
      { name: 'Maraschino cherry', measure: '1' },
      { name: 'Orange slice', measure: '1' },
    ],
  },
  {
    id: '97',
    name: 'Lynchburg Lemonade',
    image: 'https://www.thecocktaildb.com/images/media/drink/m6tqkz1487603652.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Highball glass',
    instructions: 'Shake whiskey, triple sec, and lemon juice with ice. Strain into highball glass over ice and top with lemon-lime soda. Garnish with lemon wedge.',
    ingredients: [
      { name: 'Tennessee whiskey', measure: '1 oz' },
      { name: 'Triple sec', measure: '1 oz' },
      { name: 'Sour mix', measure: '1 oz' },
      { name: 'Lemon-lime soda', measure: 'Top' },
      { name: 'Lemon wedge', measure: '1' },
    ],
  },
  {
    id: '98',
    name: 'Pickleback',
    image: 'https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg',
    category: 'Shot',
    alcoholic: 'Alcoholic',
    glass: 'Shot glass',
    instructions: 'Serve whiskey shot with pickle juice chaser.',
    ingredients: [
      { name: 'Whiskey', measure: '1 oz' },
      { name: 'Pickle juice', measure: '1 oz' },
    ],
  },
  {
    id: '99',
    name: 'Irish Coffee',
    image: 'https://www.thecocktaildb.com/images/media/drink/sywsqw1439906999.jpg',
    category: 'Coffee',
    alcoholic: 'Alcoholic',
    glass: 'Irish coffee cup',
    instructions: 'Heat the coffee, whiskey and sugar; do not boil. Pour into glass and top with cream; serve hot.',
    ingredients: [
      { name: 'Irish whiskey', measure: '1 oz' },
      { name: 'Coffee', measure: '6 oz' },
      { name: 'Sugar', measure: '2 tsp' },
      { name: 'Heavy cream', measure: '1 oz' },
    ],
  },
  {
    id: '100',
    name: 'Hot Toddy',
    image: 'https://www.thecocktaildb.com/images/media/drink/rlksyz1487603512.jpg',
    category: 'Coffee',
    alcoholic: 'Alcoholic',
    glass: 'Irish coffee cup',
    instructions: 'Combine whiskey, honey, and lemon juice in Irish coffee cup. Top with hot water and stir. Garnish with lemon wheel and cinnamon stick.',
    ingredients: [
      { name: 'Whiskey', measure: '2 oz' },
      { name: 'Honey', measure: '1 tbsp' },
      { name: 'Lemon juice', measure: '1/2 oz' },
      { name: 'Hot water', measure: '4 oz' },
      { name: 'Lemon wheel', measure: '1' },
      { name: 'Cinnamon stick', measure: '1' },
    ],
  },
  {
    id: '101',
    name: 'Hot Buttered Rum',
    image: 'https://www.thecocktaildb.com/images/media/drink/7gttqm1493068110.jpg',
    category: 'Coffee',
    alcoholic: 'Alcoholic',
    glass: 'Irish coffee cup',
    instructions: 'Combine rum, butter, brown sugar, and spices in Irish coffee cup. Top with hot water and stir. Garnish with cinnamon stick.',
    ingredients: [
      { name: 'Dark rum', measure: '2 oz' },
      { name: 'Butter', measure: '1 tbsp' },
      { name: 'Brown sugar', measure: '1 tbsp' },
      { name: 'Hot water', measure: '4 oz' },
      { name: 'Cinnamon', measure: 'Pinch' },
      { name: 'Nutmeg', measure: 'Pinch' },
      { name: 'Cinnamon stick', measure: '1' },
    ],
  },
  {
    id: '102',
    name: 'Tom and Jerry',
    image: 'https://www.thecocktaildb.com/images/media/drink/tstwau1493068110.jpg',
    category: 'Coffee',
    alcoholic: 'Alcoholic',
    glass: 'Irish coffee cup',
    instructions: 'Beat egg, sugar, and spices to create batter. Add rum and cognac to mug with 1 tbsp batter. Top with hot milk and stir. Garnish with nutmeg.',
    ingredients: [
      { name: 'Dark rum', measure: '1 oz' },
      { name: 'Cognac', measure: '1 oz' },
      { name: 'Egg', measure: '1' },
      { name: 'Sugar', measure: '1 tbsp' },
      { name: 'Hot milk', measure: '4 oz' },
      { name: 'Nutmeg', measure: 'Pinch' },
    ],
  },
  {
    id: '103',
    name: 'Eggnog',
    image: 'https://www.thecocktaildb.com/images/media/drink/fvsjqv1493068110.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Old-fashioned glass',
    instructions: 'Shake all ingredients with ice and strain into old-fashioned glass. Garnish with nutmeg.',
    ingredients: [
      { name: 'Bourbon', measure: '1 oz' },
      { name: 'Dark rum', measure: '1 oz' },
      { name: 'Cognac', measure: '1 oz' },
      { name: 'Egg', measure: '1' },
      { name: 'Heavy cream', measure: '2 oz' },
      { name: 'Simple syrup', measure: '1/2 oz' },
      { name: 'Nutmeg', measure: 'Pinch' },
    ],
  },
  {
    id: '104',
    name: 'Moscow Mule Variation',
    image: 'https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Copper mug',
    instructions: 'Muddle mint in copper mug. Add vodka and lime juice. Fill with ice and top with ginger beer. Garnish with lime wedge and mint sprig.',
    ingredients: [
      { name: 'Vodka', measure: '2 oz' },
      { name: 'Ginger beer', measure: '4 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Mint', measure: '6 leaves' },
      { name: 'Lime wedge', measure: '1' },
      { name: 'Mint sprig', measure: '1' },
    ],
  },
  {
    id: '105',
    name: 'Kentucky Mule',
    image: 'https://www.thecocktaildb.com/images/media/drink/dxxqh71630406543.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Copper mug',
    instructions: 'Combine bourbon and lime juice in copper mug filled with ice. Top with ginger beer and stir. Garnish with lime wedge.',
    ingredients: [
      { name: 'Bourbon', measure: '2 oz' },
      { name: 'Ginger beer', measure: '4 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  },
  {
    id: '106',
    name: 'Mexican Mule',
    image: 'https://www.thecocktaildb.com/images/media/drink/h0xsao1630406543.jpg',
    category: 'Cocktail',
    alcoholic: 'Alcoholic',
    glass: 'Copper mug',
    instructions: 'Combine tequila and lime juice in copper mug filled with ice. Top with ginger beer and stir. Garnish with lime wedge.',
    ingredients: [
      { name: 'Tequila', measure: '2 oz' },
      { name: 'Ginger beer', measure: '4 oz' },
      { name: 'Lime juice', measure: '1/2 oz' },
      { name: 'Lime wedge', measure: '1' },
    ],
  }
];

// This simulates an API for now - in a real app, we'd fetch from a real API
export const getAllCocktails = (): Promise<Cocktail[]> => {
  return Promise.resolve(cocktailsData);
};

export const getCocktailById = (id: string): Promise<Cocktail | undefined> => {
  const cocktail = cocktailsData.find(c => c.id === id);
  return Promise.resolve(cocktail);
};

export const searchCocktails = (query: string): Promise<Cocktail[]> => {
  const normalizedQuery = query.toLowerCase().trim();
  
  // If no query, return all cocktails
  if (!normalizedQuery) {
    return getAllCocktails();
  }
  
  // Search by name or ingredients
  const results = cocktailsData.filter(cocktail => 
    cocktail.name.toLowerCase().includes(normalizedQuery) || 
    cocktail.ingredients.some(ing => ing.name.toLowerCase().includes(normalizedQuery))
  );
  
  return Promise.resolve(results);
};

// Get list of all unique ingredients across all cocktails
export const getAllIngredients = async (): Promise<string[]> => {
  const cocktails = await getAllCocktails();
  const ingredientSet = new Set<string>();
  
  cocktails.forEach(cocktail => {
    cocktail.ingredients.forEach(ing => {
      ingredientSet.add(ing.name);
    });
  });
  
  return Array.from(ingredientSet).sort();
};

// Find cocktails that contain ALL of the provided ingredients (AND logic)
export const getCocktailsByIngredients = async (ingredients: string[]): Promise<Cocktail[]> => {
  if (!ingredients.length) return [];
  
  const cocktails = await getAllCocktails();
  const normalizedIngredients = ingredients.map(ing => ing.toLowerCase().trim());
  
  console.log('Searching for ingredients:', normalizedIngredients);
  
  // Check which cocktails contain ALL of the provided ingredients
  const results = cocktails.filter(cocktail => {
    const cocktailIngredients = cocktail.ingredients.map(ing => ing.name.toLowerCase().trim());
    console.log(`Checking ${cocktail.name}:`, cocktailIngredients);
    
    // Check if ALL selected ingredients are present in this cocktail
    const hasAllIngredients = normalizedIngredients.every(selectedIng => 
      cocktailIngredients.some(cocktailIng => 
        cocktailIng.includes(selectedIng) || selectedIng.includes(cocktailIng)
      )
    );
    
    console.log(`${cocktail.name} has all ingredients:`, hasAllIngredients);
    return hasAllIngredients;
  });
  
  console.log('Found cocktails:', results.map(c => c.name));
  return results;
};
